"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ExcluirCliente = exports.AlterarCliente = exports.ListarClientes = exports.CadastrarCliente = void 0;
var cadastrarCliente_1 = require("./cadastrarCliente");
exports.CadastrarCliente = cadastrarCliente_1.default;
var listarClientes_1 = require("./listarClientes");
exports.ListarClientes = listarClientes_1.default;
var alterarCliente_1 = require("./alterarCliente");
exports.AlterarCliente = alterarCliente_1.default;
var excluirCliente_1 = require("./excluirCliente");
exports.ExcluirCliente = excluirCliente_1.default;
