"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ExcluirProduto = exports.AlterarProduto = exports.ListarProdutos = exports.CadastrarProduto = void 0;
var cadastrarProduto_1 = require("./cadastrarProduto");
exports.CadastrarProduto = cadastrarProduto_1.default;
var listarProdutos_1 = require("./listarProdutos");
exports.ListarProdutos = listarProdutos_1.default;
var alterarProduto_1 = require("./alterarProduto");
exports.AlterarProduto = alterarProduto_1.default;
var excluirProduto_1 = require("./excluirProduto");
exports.ExcluirProduto = excluirProduto_1.default;
