"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ListarProdutosMaisConsumidosGenero = exports.ListarProdutosMaisConsumidos = exports.ListarClientesPorGenero = exports.ListarClientesConsumidores = void 0;
var clientesConsumidores_1 = require("./clientesConsumidores");
exports.ListarClientesConsumidores = clientesConsumidores_1.default;
var clientesPorGenero_1 = require("./clientesPorGenero");
exports.ListarClientesPorGenero = clientesPorGenero_1.default;
var produtosMaisConsumidos_1 = require("./produtosMaisConsumidos");
exports.ListarProdutosMaisConsumidos = produtosMaisConsumidos_1.default;
var produtosMaisConsumidosGenero_1 = require("./produtosMaisConsumidosGenero");
exports.ListarProdutosMaisConsumidosGenero = produtosMaisConsumidosGenero_1.default;
